# Generated by Django 5.1.7 on 2025-05-28 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='kkexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('exam_date', models.DateTimeField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(upload_to='exam_images/', verbose_name='Изображение задания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный экзамен')),
                ('users', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
    ]
